service: myservice # NOTE: update this with your service name

provider:
  name: aws
  runtime: ruby2.5

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
          