service: payroll-java-example

provider:
  name: aws
  runtime: java8
  region: us-west-2

package:
  artifact: target/hello-dev.jar

functions:
  payroll-controller:
    handler: com.serverless.PayrollController
    events:
      - http:
          path: /
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            